name: Bug Report
description: Create a report to help us improve ProjectSwipe
title: '[BUG] '
labels: ['bug', 'triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        Please search existing issues before creating a new one to avoid duplicates.

  - type: checkboxes
    id: platform
    attributes:
      label: Platform
      description: Which platform(s) are affected?
      options:
        - label: Android
        - label: Backend/API
        - label: Web Interface
        - label: Other (specify in description)

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened?
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 📷 Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain your problem.
      placeholder: Drag and drop images/videos here or paste URLs

  - type: textarea
    id: environment
    attributes:
      label: 🔧 Environment Information
      description: Please complete the following information
      placeholder: |
        - Device: [e.g. Samsung Galaxy S21, iPhone 13]
        - OS: [e.g. Android 12, iOS 15.1]
        - App Version: [e.g. 1.2.3]
        - Browser (if web): [e.g. Chrome 96, Safari 15]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📋 Logs/Error Messages
      description: If applicable, add relevant logs or error messages
      placeholder: Paste any relevant logs, error messages, or stack traces here
      render: shell

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Severity
      description: How severe is this bug?
      options:
        - Low - Minor inconvenience
        - Medium - Affects functionality but has workarounds
        - High - Major functionality broken
        - Critical - App crashes or data loss
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the requested information above
          required: true
        - label: I am willing to help test the fix when available
          required: false