name: Android CI

on:
  push:
    branches: [ main, develop ]
    paths: ['code/**']  # Only run when Android code changes
  pull_request:
    branches: [ main ]
    paths: ['code/**']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Get your code
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Step 2: Install Java 11 (matches your build.gradle)
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    # Step 3: Cache Gradle dependencies (speeds up builds)
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('code/**/*.gradle*', 'code/**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
        
    # Step 4: Make gradlew executable
    - name: Grant execute permission for gradlew
      run: chmod +x code/gradlew
      
    # Step 5: Build Debug APK
    - name: Build Debug APK
      run: cd code && ./gradlew assembleDebug
      
    # Step 6: Run Unit Tests
    - name: Run Unit Tests
      run: cd code && ./gradlew test
      
    # Step 7: Run Android Lint (code quality check)
    - name: Run Android Lint
      run: cd code && ./gradlew lint
      
    # Step 8: Upload APK for Download
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: ProjectSwipe-Debug-APK
        path: code/app/build/outputs/apk/debug/*.apk
        
    # Step 9: Upload Test Results (if tests fail)
    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-reports
        path: code/app/build/reports/tests/
        
    # Step 10: Upload Lint Results
    - name: Upload Lint Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lint-reports
        path: code/app/build/reports/lint-results*.html
